In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([1, 2, 3])
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
print(tensor_two_d)


tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32)


In [10]:
tensor_tree_d = tf.constant([[[1,2,3],[3,4,5]],[[4,5,6],[6,7,8]],[[43,53,63],[63,73,83]]])
print(tensor_tree_d)


tf.Tensor(
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 6  7  8]]

 [[43 53 63]
  [63 73 83]]], shape=(3, 2, 3), dtype=int32)
