In [1]:
import tensorflow as tf

In [3]:
x_1 = tf.constant([[2,3,43],[3,4,5]])
x_2 = tf.constant([[2,3,4,5,56],[3,5,6,7,8],[6,5,6,7,78]])
tf.linalg.matmul(x_1,x_2)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 271,  236,  284,  332, 3490],
       [  48,   54,   66,   78,  590]])>

In [29]:
tf.linalg.band_part(x_2, 0,4)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[ 2,  3,  4,  5, 56],
       [ 0,  5,  6,  7,  8],
       [ 0,  0,  6,  7, 78]])>