In [1]:
import tensorflow as tf

In [2]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [5]:
x_1 = tf.constant([5,4,5,6,7,8,9,5,4,3])
x_2 = tf.constant([4,5,6,7,8,6,4,3,2,4])
print(tf.add(x_1,x_2))
print(tf.math.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))


tf.Tensor([ 9  9 11 13 15 14 13  8  6  7], shape=(10,), dtype=int32)
tf.Tensor([ 1 -1 -1 -1 -1  2  5  2  2 -1], shape=(10,), dtype=int32)
tf.Tensor([20 20 30 42 56 48 36 15  8 12], shape=(10,), dtype=int32)
tf.Tensor(
[1.25       0.8        0.83333333 0.85714286 0.875      1.33333333
 2.25       1.66666667 2.         0.75      ], shape=(10,), dtype=float64)


In [8]:
x_3 = tf.constant([[5,3,4,5,6,7],],dtype=tf.float32)
x_4 = tf.constant([[7],[5],[3],], dtype=tf.float32)

print(tf.math.multiply(x_3,x_4))

tf.Tensor(
[[35. 21. 28. 35. 42. 49.]
 [25. 15. 20. 25. 30. 35.]
 [15.  9. 12. 15. 18. 21.]], shape=(3, 6), dtype=float32)


In [1]:
x_argmax = tf.math.argmax(tf.constant([200,120,130,3,6]))
print(x_argmax)

NameError: name 'tf' is not defined